// Copyright (c) 2025-2026 Gabriel Lars Sabadin
// Licensed under the MIT License. See LICENSE file in the project root.
// Created: 2026-03-24

//! CLAUDE.md generation from a PACT program.
//!
//! Produces a single Markdown file that encodes the project's agent system
//! as process memory for Claude Code. The output includes agent definitions,
//! flow step sequences, data schemas, permission rules, learned lessons,
//! MCP connections, and task management guidance.
//!
//! ## Usage
//!
//! ```no_run
//! use pact_build::emit_claude_md::generate_claude_md;
//! use pact_build::config::{BuildConfig, Target};
//! use pact_core::ast::stmt::Program;
//!
//! # fn example(program: Program) {
//! let config = BuildConfig::new("example.pact", "./pact-out", Target::Claude);
//! let md = generate_claude_md(&program, &config);
//! std::fs::write("CLAUDE.md", md).unwrap();
//! # }
//! ```

use pact_core::ast::expr::ExprKind;
use pact_core::ast::stmt::{DeclKind, Program};
use pact_core::ast::types::TypeExprKind;

use crate::config::BuildConfig;

/// All known permission categories and their human-readable descriptions.
const ALL_PERMISSION_CATEGORIES: &[(&str, &str)] = &[
    ("net.read", "read data from the network"),
    ("net.write", "send data over the network"),
    ("fs.read", "read files from the filesystem"),
    ("fs.write", "write or modify files on the filesystem"),
    ("llm.query", "query language models"),
    ("db.read", "read from databases"),
    ("db.write", "write to databases"),
    ("exec.run", "execute system commands"),
    ("email.send", "send emails"),
    ("pay.charge", "process payments"),
];

/// Generate a complete CLAUDE.md file from a checked PACT program.
///
/// The output encodes the project's agent system as process memory for
/// Claude Code, including agents, flows, schemas, permission rules,
/// lessons, MCP connections, and task management guidance.
pub fn generate_claude_md(program: &Program, config: &BuildConfig) -> String {
    let mut md = String::new();

    // Project header
    let project_name = config
        .source_name()
        .strip_suffix(".pact")
        .unwrap_or(config.source_name());
    md.push_str(&format!("# {}\n\n", project_name));
    md.push_str(&format!(
        "> Auto-generated by `pact build --claude-md` from {}\n\n",
        config.source_name()
    ));

    // Agents section
    let agents_section = generate_agents_section(program);
    if !agents_section.is_empty() {
        md.push_str(&agents_section);
    }

    // Flows section
    let flows_section = generate_flows_section(program);
    if !flows_section.is_empty() {
        md.push_str(&flows_section);
    }

    // Data Schemas section
    let schemas_section = generate_schemas_section(program);
    if !schemas_section.is_empty() {
        md.push_str(&schemas_section);
    }

    // Rules section
    let rules_section = generate_rules_section(program);
    if !rules_section.is_empty() {
        md.push_str(&rules_section);
    }

    // Learned Lessons section
    let lessons_section = generate_lessons_section(program);
    if !lessons_section.is_empty() {
        md.push_str(&lessons_section);
    }

    // Compliance section
    let compliance_section = generate_compliance_section(program);
    if !compliance_section.is_empty() {
        md.push_str(&compliance_section);
    }

    // Task Management section (only if there are flows)
    let has_flows = program
        .decls
        .iter()
        .any(|d| matches!(&d.kind, DeclKind::Flow(_)));
    if has_flows {
        md.push_str(&generate_task_management_section());
    }

    // MCP Connections section
    let connect_section = generate_connect_section(program);
    if !connect_section.is_empty() {
        md.push_str(&connect_section);
    }

    md
}

/// Generate the Agents section listing each agent's role, capabilities, and tools.
fn generate_agents_section(program: &Program) -> String {
    let agents: Vec<_> = program
        .decls
        .iter()
        .filter_map(|d| match &d.kind {
            DeclKind::Agent(a) => Some(a),
            _ => None,
        })
        .collect();

    if agents.is_empty() {
        return String::new();
    }

    let mut md = String::from("## Agents\n\n");

    for agent in agents {
        md.push_str(&format!("### @{}\n", agent.name));

        // Role (from prompt)
        if let Some(prompt_expr) = &agent.prompt {
            let text = extract_text(prompt_expr);
            if !text.is_empty() {
                md.push_str(&format!("**Role:** {}\n", text));
            }
        }

        // Capabilities (permissions)
        let perms: Vec<String> = agent
            .permits
            .iter()
            .filter_map(|e| match &e.kind {
                ExprKind::PermissionRef(segs) => Some(format!("^{}", segs.join("."))),
                _ => None,
            })
            .collect();
        if !perms.is_empty() {
            md.push_str(&format!("**Capabilities:** {}\n", perms.join(", ")));
        }

        // Tools
        let tools: Vec<String> = agent
            .tools
            .iter()
            .filter_map(|e| match &e.kind {
                ExprKind::ToolRef(name) => Some(format!("#{}", name)),
                _ => None,
            })
            .collect();
        if !tools.is_empty() {
            md.push_str(&format!("**Tools:** {}\n", tools.join(", ")));
        }

        md.push('\n');
    }

    md
}

/// Generate the Flows section with numbered step sequences.
fn generate_flows_section(program: &Program) -> String {
    let flows: Vec<_> = program
        .decls
        .iter()
        .filter_map(|d| match &d.kind {
            DeclKind::Flow(f) => Some(f),
            _ => None,
        })
        .collect();

    if flows.is_empty() {
        return String::new();
    }

    let mut md = String::from("## Flows\n\n");

    for flow in flows {
        // Flow signature
        let params_str = flow
            .params
            .iter()
            .map(|p| {
                if let Some(ty) = &p.ty {
                    format!("{} :: {}", p.name, format_type(ty))
                } else {
                    p.name.clone()
                }
            })
            .collect::<Vec<_>>()
            .join(", ");

        let return_str = flow
            .return_type
            .as_ref()
            .map(|ty| format!(" -> {}", format_type(ty)))
            .unwrap_or_default();

        md.push_str(&format!(
            "### {}({}){}\n",
            flow.name, params_str, return_str
        ));

        // Extract steps from body
        let mut step_num = 1;
        for expr in &flow.body {
            if let ExprKind::Assign { name, value } = &expr.kind {
                if let ExprKind::AgentDispatch { agent, tool, args } = &value.kind {
                    let agent_name = extract_ref_name(agent);
                    let tool_name = extract_ref_name(tool);
                    let args_str = args
                        .iter()
                        .map(format_expr_brief)
                        .collect::<Vec<_>>()
                        .join(", ");
                    md.push_str(&format!(
                        "{}. `{}` = @{} -> #{}({})\n",
                        step_num, name, agent_name, tool_name, args_str
                    ));
                    step_num += 1;
                }
            }
        }

        md.push('\n');
    }

    md
}

/// Generate the Data Schemas section with field tables.
fn generate_schemas_section(program: &Program) -> String {
    let schemas: Vec<_> = program
        .decls
        .iter()
        .filter_map(|d| match &d.kind {
            DeclKind::Schema(s) => Some(s),
            _ => None,
        })
        .collect();

    if schemas.is_empty() {
        return String::new();
    }

    let mut md = String::from("## Data Schemas\n\n");

    for schema in schemas {
        md.push_str(&format!("### {}\n", schema.name));
        md.push_str("| Field | Type |\n");
        md.push_str("|-------|------|\n");
        for field in &schema.fields {
            md.push_str(&format!(
                "| {} | {} |\n",
                field.name,
                format_type(&field.ty)
            ));
        }
        md.push('\n');
    }

    md
}

/// Generate the Rules section with MUST NOT rules for denied permissions.
fn generate_rules_section(program: &Program) -> String {
    let agents: Vec<_> = program
        .decls
        .iter()
        .filter_map(|d| match &d.kind {
            DeclKind::Agent(a) => Some(a),
            _ => None,
        })
        .collect();

    if agents.is_empty() {
        return String::new();
    }

    let mut rules = Vec::new();

    for agent in &agents {
        let granted: Vec<String> = agent
            .permits
            .iter()
            .filter_map(|e| match &e.kind {
                ExprKind::PermissionRef(segs) => Some(segs.join(".")),
                _ => None,
            })
            .collect();

        for (perm, description) in ALL_PERMISSION_CATEGORIES {
            let is_covered = granted.iter().any(|g| permission_covers(g, perm));
            if !is_covered {
                rules.push(format!(
                    "- @{} MUST NOT {} (no ^{})",
                    agent.name, description, perm
                ));
            }
        }
    }

    if rules.is_empty() {
        return String::new();
    }

    let mut md = String::from("## Rules\n\n");
    for rule in &rules {
        md.push_str(rule);
        md.push('\n');
    }
    md.push('\n');

    md
}

/// Generate the Learned Lessons section.
fn generate_lessons_section(program: &Program) -> String {
    let lessons: Vec<_> = program
        .decls
        .iter()
        .filter_map(|d| match &d.kind {
            DeclKind::Lesson(l) => Some(l),
            _ => None,
        })
        .collect();

    if lessons.is_empty() {
        return String::new();
    }

    let mut md = String::from("## Learned Lessons\n\n");

    for lesson in lessons {
        let severity_label = lesson.severity.as_deref().unwrap_or("info");
        let rule_text = lesson.rule.as_deref().unwrap_or("");

        md.push_str(&format!(
            "- **{}** ({}): {}\n",
            lesson.name, severity_label, rule_text
        ));

        if let Some(context) = &lesson.context {
            md.push_str(&format!("  _Context: {}_\n", context));
        }
    }
    md.push('\n');

    md
}

/// Generate the Compliance section.
fn generate_compliance_section(program: &Program) -> String {
    let compliances: Vec<_> = program
        .decls
        .iter()
        .filter_map(|d| match &d.kind {
            DeclKind::Compliance(c) => Some(c),
            _ => None,
        })
        .collect();

    if compliances.is_empty() {
        return String::new();
    }

    let mut md = String::from("## Compliance\n\n");

    for c in compliances {
        md.push_str(&format!("### {}\n", c.name));

        if let Some(risk) = &c.risk {
            md.push_str(&format!("**Risk:** {}\n", risk));
        }
        if !c.frameworks.is_empty() {
            md.push_str(&format!("**Frameworks:** {}\n", c.frameworks.join(", ")));
        }
        if let Some(audit) = &c.audit {
            md.push_str(&format!("**Audit:** {}\n", audit));
        }
        if let Some(retention) = &c.retention {
            md.push_str(&format!("**Retention:** {}\n", retention));
        }
        if let Some(interval) = &c.review_interval {
            md.push_str(&format!("**Review Interval:** {}\n", interval));
        }
        if !c.roles.is_empty() {
            md.push_str("**Roles:**\n");
            for role in &c.roles {
                md.push_str(&format!("- {}: {}\n", role.role, role.assignee));
            }
        }

        md.push('\n');
    }

    md
}

/// Generate the static Task Management section.
fn generate_task_management_section() -> String {
    let mut md = String::from("## Task Management\n\n");
    md.push_str("When executing flows in this project:\n");
    md.push_str("1. **Plan**: Review flow steps and identify required agents\n");
    md.push_str("2. **Verify permissions**: Ensure each agent has the capabilities it needs\n");
    md.push_str(
        "3. **Execute sequentially**: Follow step order \
         — each step's output feeds the next\n",
    );
    md.push_str("4. **Validate output**: Check results match declared return types and schemas\n");
    md.push_str("5. **Report**: Summarize execution, flag any permission violations or failures\n");
    md.push('\n');
    md
}

/// Generate the MCP Connections section.
fn generate_connect_section(program: &Program) -> String {
    let connects: Vec<_> = program
        .decls
        .iter()
        .filter_map(|d| match &d.kind {
            DeclKind::Connect(c) => Some(c),
            _ => None,
        })
        .collect();

    let servers: Vec<_> = connects.iter().flat_map(|c| &c.servers).collect();

    if servers.is_empty() {
        return String::new();
    }

    let mut md = String::from("## MCP Connections\n\n");
    md.push_str("| Server | Transport |\n");
    md.push_str("|--------|----------|\n");
    for entry in servers {
        md.push_str(&format!("| {} | {} |\n", entry.name, entry.transport));
    }
    md.push('\n');

    md
}

/// Check if a granted permission covers a target permission.
/// `"net"` covers `"net.read"` and `"net.write"`.
fn permission_covers(granted: &str, target: &str) -> bool {
    granted == target || target.starts_with(&format!("{}.", granted))
}

/// Extract text from a PromptLit or StringLit expression.
fn extract_text(expr: &pact_core::ast::expr::Expr) -> String {
    match &expr.kind {
        ExprKind::PromptLit(s) | ExprKind::StringLit(s) => s.trim().to_string(),
        _ => String::new(),
    }
}

/// Extract the reference name from an AgentRef, ToolRef, or Ident expression.
fn extract_ref_name(expr: &pact_core::ast::expr::Expr) -> String {
    match &expr.kind {
        ExprKind::AgentRef(name) => name.clone(),
        ExprKind::ToolRef(name) => name.clone(),
        ExprKind::Ident(name) => name.clone(),
        _ => "unknown".to_string(),
    }
}

/// Format an expression as a brief string for display in flow steps.
fn format_expr_brief(expr: &pact_core::ast::expr::Expr) -> String {
    match &expr.kind {
        ExprKind::Ident(name) => name.clone(),
        ExprKind::StringLit(s) => format!("\"{}\"", s),
        ExprKind::PromptLit(s) => format!("<<{}>>", s.trim()),
        ExprKind::IntLit(n) => n.to_string(),
        ExprKind::FloatLit(f) => f.to_string(),
        ExprKind::BoolLit(b) => b.to_string(),
        ExprKind::AgentRef(name) => format!("@{}", name),
        ExprKind::ToolRef(name) => format!("#{}", name),
        ExprKind::FieldAccess { object, field } => {
            format!("{}.{}", format_expr_brief(object), field)
        }
        _ => "_".to_string(),
    }
}

/// Format a type expression for display.
fn format_type(ty: &pact_core::ast::types::TypeExpr) -> String {
    match &ty.kind {
        TypeExprKind::Named(n) => n.clone(),
        TypeExprKind::Generic { name, args } => {
            let arg_strs: Vec<String> = args.iter().map(format_type).collect();
            format!("{}<{}>", name, arg_strs.join(", "))
        }
        TypeExprKind::Optional(inner) => format!("{}?", format_type(inner)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Target;
    use pact_core::ast::stmt::Program;
    use pact_core::lexer::Lexer;
    use pact_core::parser::Parser;
    use pact_core::span::SourceMap;

    fn parse_program(src: &str) -> Program {
        let mut sm = SourceMap::new();
        let id = sm.add("test.pact", src);
        let tokens = Lexer::new(src, id).lex().unwrap();
        Parser::new(&tokens).parse().unwrap()
    }

    fn test_config() -> BuildConfig {
        BuildConfig::new("example.pact", "/tmp/pact-test", Target::Claude)
    }

    #[test]
    fn claude_md_agent_section() {
        let src = r#"
            agent @researcher {
                permits: [^net.read, ^llm.query]
                tools: [#search, #summarize]
                model: "claude-sonnet-4-20250514"
                prompt: <<You are a thorough research assistant.>>
            }
            agent @writer {
                permits: [^llm.query, ^fs.write]
                tools: [#draft]
                prompt: <<You write polished content.>>
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## Agents"));
        assert!(md.contains("### @researcher"));
        assert!(md.contains("**Role:** You are a thorough research assistant."));
        assert!(md.contains("**Capabilities:** ^net.read, ^llm.query"));
        assert!(md.contains("**Tools:** #search, #summarize"));
        assert!(md.contains("### @writer"));
        assert!(md.contains("**Role:** You write polished content."));
        assert!(md.contains("**Capabilities:** ^llm.query, ^fs.write"));
        assert!(md.contains("**Tools:** #draft"));
    }

    #[test]
    fn claude_md_flow_steps() {
        let src = r#"
            agent @researcher {
                permits: [^net.read, ^llm.query]
                tools: [#search]
                prompt: <<Research.>>
            }
            agent @writer {
                permits: [^llm.query]
                tools: [#draft]
                prompt: <<Write.>>
            }
            flow write_article(topic :: String) -> String {
                research = @researcher -> #search(topic)
                article = @writer -> #draft(research)
                return article
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## Flows"));
        assert!(md.contains("### write_article(topic :: String) -> String"));
        assert!(md.contains("1. `research` = @researcher -> #search(topic)"));
        assert!(md.contains("2. `article` = @writer -> #draft(research)"));
    }

    #[test]
    fn claude_md_permission_rules() {
        let src = r#"
            agent @limited {
                permits: [^llm.query]
                tools: []
                prompt: <<A limited agent.>>
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## Rules"));
        assert!(md.contains("@limited MUST NOT read data from the network (no ^net.read)"));
        assert!(md.contains("@limited MUST NOT send data over the network (no ^net.write)"));
        assert!(md.contains("@limited MUST NOT read files from the filesystem (no ^fs.read)"));
        assert!(
            md.contains("@limited MUST NOT write or modify files on the filesystem (no ^fs.write)")
        );
        // llm.query IS granted, so it should NOT appear as a MUST NOT rule
        assert!(!md.contains("@limited MUST NOT query language models"));
    }

    #[test]
    fn claude_md_lessons_section() {
        let src = r#"
            lesson "cache_invalidation" {
                context: <<After deploy, cache was stale for 10 minutes>>
                rule: <<Always invalidate CDN cache after deploy>>
                severity: warning
            }
            lesson "retry_backoff" {
                rule: <<Use exponential backoff for retries>>
                severity: info
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## Learned Lessons"));
        assert!(md.contains(
            "**cache_invalidation** (warning): Always invalidate CDN cache after deploy"
        ));
        assert!(md.contains("_Context: After deploy, cache was stale for 10 minutes_"));
        assert!(md.contains("**retry_backoff** (info): Use exponential backoff for retries"));
    }

    #[test]
    fn claude_md_connect_section() {
        let src = r#"
            connect {
                slack   "stdio slack-mcp-server"
                github  "sse https://github.internal/mcp"
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## MCP Connections"));
        assert!(md.contains("| Server | Transport |"));
        assert!(md.contains("| slack | stdio slack-mcp-server |"));
        assert!(md.contains("| github | sse https://github.internal/mcp |"));
    }

    #[test]
    fn claude_md_schemas_section() {
        let src = r#"
            schema Article {
                title :: String
                body :: String
                tags :: List<String>
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## Data Schemas"));
        assert!(md.contains("### Article"));
        assert!(md.contains("| title | String |"));
        assert!(md.contains("| body | String |"));
        assert!(md.contains("| tags | List<String> |"));
    }

    #[test]
    fn claude_md_empty_sections_omitted() {
        // A program with only an agent — no flows, schemas, lessons, or connections
        let src = r#"
            agent @solo {
                permits: [^llm.query]
                tools: []
                prompt: <<Just an agent.>>
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## Agents"));
        assert!(md.contains("## Rules"));
        assert!(!md.contains("## Flows"));
        assert!(!md.contains("## Data Schemas"));
        assert!(!md.contains("## Learned Lessons"));
        assert!(!md.contains("## Task Management"));
        assert!(!md.contains("## MCP Connections"));
    }

    #[test]
    fn claude_md_task_management_with_flows() {
        let src = r#"
            agent @worker {
                permits: [^llm.query]
                tools: [#task]
                prompt: <<Work.>>
            }
            flow do_work(input :: String) -> String {
                result = @worker -> #task(input)
                return result
            }
        "#;
        let program = parse_program(src);
        let md = generate_claude_md(&program, &test_config());

        assert!(md.contains("## Task Management"));
        assert!(md.contains("1. **Plan**: Review flow steps"));
        assert!(md.contains("2. **Verify permissions**"));
        assert!(md.contains("3. **Execute sequentially**"));
        assert!(md.contains("4. **Validate output**"));
        assert!(md.contains("5. **Report**"));
    }

    #[test]
    fn claude_md_header() {
        let src = "agent @x { permits: [] tools: [] }";
        let program = parse_program(src);
        let config = BuildConfig::new("website_builder.pact", "/tmp/out", Target::Claude);
        let md = generate_claude_md(&program, &config);

        assert!(md.contains("# website_builder"));
        assert!(
            md.contains("> Auto-generated by `pact build --claude-md` from website_builder.pact")
        );
    }

    #[test]
    fn claude_md_parent_permission_coverage() {
        // If an agent has ^net (parent), it should cover net.read and net.write
        // so those should NOT appear as MUST NOT rules.
        // Note: the parser may or may not support bare ^net; test the logic directly.
        assert!(permission_covers("net", "net.read"));
        assert!(permission_covers("net", "net.write"));
        assert!(permission_covers("llm.query", "llm.query"));
        assert!(!permission_covers("net.read", "net.write"));
        assert!(!permission_covers("fs", "net.read"));
    }
}
